---
output: html_document
editor_options: 
  chunk_output_type: console
---

RUN ALWAYS

Prepare session and loading functions.

```{r}
rm(list = ls())
options(stringsAsFactors = FALSE)
source("/home/jaume/Projects/BreastMapper/Functions/Functions_Breast.R")
```

Installing SurvMap and loading it into the environment.

```{r}
library(devtools) #Loading devtools
#install_github("jfores/SurvMap") #Installing SurvMap
library(SurvMap) #Loading SurvMap.
```

STARTING POINT 1


Loading the complete breast cancer dataset.

```{r}
list_MM_frma <- get(load(file = "/home/jaume/Projects/BreastMapper/Data/Interm_DS/list_MM_frma.Rda"))
eData_frma_MM <- list_MM_frma[[1]]
pData_frma_MM <- list_MM_frma[[2]]
table(colnames(eData_frma_MM) == rownames(pData_frma_MM))
table(pData_frma_MM$pCh_Status)
```

Divide dataset into two blocks of the same size.

```{r}
source("/home/jaume/Projects/BreastMapper/Functions/Functions_Breast.R")

ds_splitted <- divide_ds_two(eData_frma_MM,pData_frma_MM)
save(file = "/media/data/jaume/BreastCancer/Analysis_Mapper/ds_splitted.Rda",ds_splitted)
```

STARTING POINT 2

Loading the spited data.

```{r}
ds_splitted <- get(load(file =  "/media/data/jaume/BreastCancer/Analysis_Mapper/ds_splitted.Rda"))
exp_A <- ds_splitted[[1]][[1]]
pheno_A <- ds_splitted[[1]][[2]]
```

SurvMap Analysis dataset A.





